# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-07 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0002_auto_20190604_0925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auto',
            new_name='AutoPage',
        ),
    ]
