# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0004_auto_20190607_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopage',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='autopage',
            name='description_text',
            field=models.TextField(blank=True),
        ),
    ]
