# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0005_auto_20190610_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugpage',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='releasepage',
            name='comment_text',
        ),
        migrations.AddField(
            model_name='bugpage',
            name='description_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='description_text',
            field=models.TextField(blank=True),
        ),
    ]
