# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0006_auto_20190610_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopage',
            name='upload',
            field=models.ImageField(default='auto_images/', upload_to='auto_images/'),
        ),
        migrations.AddField(
            model_name='bugpage',
            name='upload',
            field=models.ImageField(default='bug_images/', upload_to='bug_images/'),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='upload',
            field=models.ImageField(default='release_images/', upload_to='release_images/'),
        ),
    ]
