# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0009_auto_20190626_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='autopage',
            name='link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tvision.AutoLink'),
            preserve_default=False,
        ),
    ]
