# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0010_auto_20190626_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autolink',
            old_name='link_name',
            new_name='link',
        ),
        migrations.AddField(
            model_name='autolink',
            name='link_title',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
