# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0015_auto_20190627_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopage',
            name='title_text',
        ),
        migrations.RemoveField(
            model_name='bugpage',
            name='title_text',
        ),
        migrations.RemoveField(
            model_name='releasepage',
            name='title_text',
        ),
        migrations.AddField(
            model_name='autolink',
            name='link_author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='autopage',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='autopage',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='buglink',
            name='link_author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bugpage',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bugpage',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='releaselink',
            name='link_author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='author',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='autolink',
            name='link_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='buglink',
            name='link_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='releaselink',
            name='link_title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
