# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0020_auto_20190627_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autopage',
            old_name='description_text',
            new_name='precondition_text',
        ),
        migrations.RenameField(
            model_name='bugpage',
            old_name='description_text',
            new_name='precondition_text',
        ),
        migrations.RenameField(
            model_name='releasepage',
            old_name='description_text',
            new_name='precondition_text',
        ),
    ]
