# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0023_auto_20190703_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoLink',
            new_name='AutomatedLink',
        ),
        migrations.RenameModel(
            old_name='AutoPage',
            new_name='AutomatedPage',
        ),
    ]
