# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-08 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0024_auto_20190708_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedpage',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='automatedpage',
            name='parameters',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='automatedpage',
            name='steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bugpage',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bugpage',
            name='parameters',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bugpage',
            name='steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='parameters',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='steps',
            field=models.TextField(blank=True),
        ),
    ]
