# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0025_auto_20190708_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayFrontImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(blank=True, default='web_images/', null=True, upload_to='web_images/')),
            ],
        ),
    ]
