# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-10 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0026_displayfrontimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=500, null=True)),
                ('dcument_author', models.CharField(max_length=500, null=True)),
                ('user_document', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BugDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=500, null=True)),
                ('document_author', models.CharField(max_length=500, null=True)),
                ('user_document', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=500, null=True)),
                ('document_author', models.CharField(max_length=500, null=True)),
                ('user_document', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='displayfrontimages',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='automatedpage',
            name='document_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvision.AutomatedDocument'),
        ),
        migrations.AddField(
            model_name='bugpage',
            name='document_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvision.BugDocument'),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='document_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvision.ReleaseDocument'),
        ),
    ]
