# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-12 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0029_auto_20190711_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automatedpage',
            old_name='upload',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='bugpage',
            old_name='upload',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='displayfrontimages',
            old_name='upload',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='releasepage',
            old_name='upload',
            new_name='image',
        ),
    ]
