# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0030_auto_20190712_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedpage',
            name='document_link',
            field=models.FileField(blank=True, default='auto_documents/', null=True, upload_to='auto_documents/'),
        ),
    ]
