# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0031_automatedpage_document_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasepage',
            name='test_suite',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
