# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0032_releasepage_test_suite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayFrontImages',
        ),
    ]
