# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-15 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvision', '0034_auto_20190715_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugpage',
            name='document_link',
            field=models.FileField(blank=True, default='auto_documents/', null=True, upload_to='auto_documents/'),
        ),
        migrations.AddField(
            model_name='releasepage',
            name='document_link',
            field=models.FileField(blank=True, default='auto_documents/', null=True, upload_to='auto_documents/'),
        ),
    ]
